package com.miaoshaproject.dataObject;

import java.math.BigDecimal;

public class OrderDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.id
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.user_id
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.item_id
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.item_price
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    private BigDecimal itemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.amount
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.order_price
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    private BigDecimal orderPrice;

    private Integer promoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.id
     *
     * @return the value of orderinfo.id
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.id
     *
     * @param id the value for orderinfo.id
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.user_id
     *
     * @return the value of orderinfo.user_id
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.user_id
     *
     * @param userId the value for orderinfo.user_id
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.item_id
     *
     * @return the value of orderinfo.item_id
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.item_id
     *
     * @param itemId the value for orderinfo.item_id
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.item_price
     *
     * @return the value of orderinfo.item_price
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.item_price
     *
     * @param itemPrice the value for orderinfo.item_price
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.amount
     *
     * @return the value of orderinfo.amount
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.amount
     *
     * @param amount the value for orderinfo.amount
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.order_price
     *
     * @return the value of orderinfo.order_price
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.order_price
     *
     * @param orderPrice the value for orderinfo.order_price
     *
     * @mbggenerated Tue Mar 05 15:31:12 CST 2019
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    public Integer getPromoId() {
        return promoId;
    }

    public void setPromoId(Integer promoId) {
        this.promoId = promoId;
    }
}