package com.miaoshaproject.dao;

import com.miaoshaproject.dataObject.ItemDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Mar 04 21:01:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Mar 04 21:01:07 CST 2019
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Mar 04 21:01:07 CST 2019
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Mar 04 21:01:07 CST 2019
     */
    ItemDo selectByPrimaryKey(Integer id);


    List<ItemDo> listItem();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Mar 04 21:01:07 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Mar 04 21:01:07 CST 2019
     */
    int updateByPrimaryKey(ItemDo record);

    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}