package com.miaoshaproject.dao;

import com.miaoshaproject.dataObject.OrderDo;

public interface OrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbggenerated Tue Mar 05 15:31:13 CST 2019
     */
    int insert(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbggenerated Tue Mar 05 15:31:13 CST 2019
     */
    int insertSelective(OrderDo record);
}